### ISSUE TITLE
Issue creating Skillset for Exercise 1 - Azure Search

### ISSUE THREAD

**Issue by sdolgin** [MicrosoftLearning/mslearn-knowledge-mining#41]
Hello,

I've attempted to follow the instructions for exercise 1 and can't proceed. At Step 14 of [Index the documents](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/main/Instructions/Exercises/01-azure-search.md#index-the-documents) I am getting an error from the portal:

> Import configuration failed, error creating Indexer
This indexer refers to a skillset 'margies-skillset' that doesn't exist

I tried to run the steps in East US, East US 2 and France Central and get the same error in each region. Also, I thought maybe I could create a skillset manually by creating one first in the portal that could then be referenced by an indexer. I modified the [skillset JSON from the lab files](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/main/Labfiles/01-azure-search/modify-search/skillset.json) to include my Azure AI Service (multi-service) key and tried to upload it through the Portal UI but received validation error "invalid product". 

Any help would be appreciated to unblock me in this exercise!

**Comment by Matlock1000D** [comment]
I had the same issue. The deployment would fail because the creation of the skillset would fail. Furthermore, I the error would flash in the UI notifications, but I was unable to find the exact reason afterwards. I am using Sweden Central since AI Search could not be created in West Europe.

Anyway, the solution seems to have been to create an **Azure AI services multi-service account**, _not_ an **Azure AI services** instance. Please fix the documentation or the underlying issue.

**Comment by ivorb** [comment]
clarified in the instructions the resource type, in e344604
